## Day 5

In [80]:
Dataset="F:\\UPX_TechM\\Data Analytic\\Practicals\\Datasets"

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

1. Function
   - lambda function
2.	exception handling
3.	sets
4.	Modules
5.	**Numpy <--**


**Numpy**

In [3]:
import numpy as np

In [4]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

```It will concat instead of addition```

In [5]:
d=[12,34,12]
s=[5,10,7]
dist=np.array(d)
speed=np.array(s)

In [6]:
time=dist/speed

In [7]:
time

array([2.4       , 3.4       , 1.71428571])

In [8]:
time.shape
len(time)
time.ndim # shows dimention of array
time.size
time.dtype
time.dtype.name
time.astype(int) # convert to int
time1=time.astype(int)
time1.dtype

(3,)

3

1

3

dtype('float64')

'float64'

array([2, 3, 1])

dtype('int32')

In [9]:
c= np.array(np.arange(10))

In [10]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
anarray=np.array(np.arange(5,61,5))

In [12]:
anarray

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [13]:
anarray_reshaped=anarray.reshape(3,4)

In [14]:
anarray_reshaped

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [15]:
anarray_reshaped.shape
anarray_reshaped.size
anarray_reshaped.dtype
anarray_reshaped.max()
anarray_reshaped.min()
anarray_reshaped.mean()
anarray_reshaped.ndim # it shows dimention of the array

(3, 4)

12

dtype('int32')

60

5

32.5

2

In [16]:
onemorearray=np.linspace(1,100,25) # create array 25 equal part

In [17]:
onemorearray

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [18]:
print(np.round(onemorearray,2))

[  1.     5.12   9.25  13.38  17.5   21.62  25.75  29.88  34.    38.12
  42.25  46.38  50.5   54.62  58.75  62.88  67.    71.12  75.25  79.38
  83.5   87.62  91.75  95.88 100.  ]


In [19]:
np.zeros(10).reshape(2,5)# we are created array of 10 zeroes shape it to 2/5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
onemorearray_transposed=onemorearray.T

In [21]:
onemorearray_transposed

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [22]:
#Logical/boolean comparison

In [23]:
(onemorearray>=50).sum()

13

In [39]:
array1=np.round(np.random.random(3).reshape(3,1),2)

In [40]:
array2=np.round(np.random.random(15).reshape(3,5),2)
array2

array([[0.6 , 0.48, 0.46, 0.28, 0.07],
       [0.6 , 0.13, 0.37, 0.6 , 0.63],
       [0.59, 0.22, 0.17, 0.2 , 0.92]])

In [41]:
array1
array2

array([[0.09],
       [0.38],
       [0.61]])

array([[0.6 , 0.48, 0.46, 0.28, 0.07],
       [0.6 , 0.13, 0.37, 0.6 , 0.63],
       [0.59, 0.22, 0.17, 0.2 , 0.92]])

In [42]:
array2.max()
array2.min()

0.92

0.07

In [43]:
array2.std()

0.23165683432372308

In [44]:
array2.cumsum()
array2.flatten()
array2.ravel()

array([0.6 , 1.08, 1.54, 1.82, 1.89, 2.49, 2.62, 2.99, 3.59, 4.22, 4.81,
       5.03, 5.2 , 5.4 , 6.32])

array([0.6 , 0.48, 0.46, 0.28, 0.07, 0.6 , 0.13, 0.37, 0.6 , 0.63, 0.59,
       0.22, 0.17, 0.2 , 0.92])

array([0.6 , 0.48, 0.46, 0.28, 0.07, 0.6 , 0.13, 0.37, 0.6 , 0.63, 0.59,
       0.22, 0.17, 0.2 , 0.92])

In [45]:
array1

array([[0.09],
       [0.38],
       [0.61]])

In [46]:
array2

array([[0.6 , 0.48, 0.46, 0.28, 0.07],
       [0.6 , 0.13, 0.37, 0.6 , 0.63],
       [0.59, 0.22, 0.17, 0.2 , 0.92]])

**This called broad casting**

In [47]:
array3=array1+array2

In [48]:
array3

array([[0.69, 0.57, 0.55, 0.37, 0.16],
       [0.98, 0.51, 0.75, 0.98, 1.01],
       [1.2 , 0.83, 0.78, 0.81, 1.53]])

In [49]:
array4=array3-array2

In [50]:
array4

array([[0.09, 0.09, 0.09, 0.09, 0.09],
       [0.38, 0.38, 0.38, 0.38, 0.38],
       [0.61, 0.61, 0.61, 0.61, 0.61]])

In [51]:
e=np.round((np.random.random(5).reshape(1,5)),2)

In [52]:
e

array([[0.56, 0.39, 0.59, 0.64, 0.28]])

In [55]:
a=array1*array2

In [56]:
a

array([[0.054 , 0.0432, 0.0414, 0.0252, 0.0063],
       [0.228 , 0.0494, 0.1406, 0.228 , 0.2394],
       [0.3599, 0.1342, 0.1037, 0.122 , 0.5612]])

In [57]:
b=array1**array2

In [58]:
b

array([[0.23580093, 0.31480122, 0.33033269, 0.50955129, 0.84488379],
       [0.55959027, 0.8818036 , 0.69906882, 0.55959027, 0.54358025],
       [0.74704128, 0.89695894, 0.91940333, 0.90587019, 0.63460494]])

In [59]:
array2.sort()

In [60]:
array2

array([[0.07, 0.28, 0.46, 0.48, 0.6 ],
       [0.13, 0.37, 0.6 , 0.6 , 0.63],
       [0.17, 0.2 , 0.22, 0.59, 0.92]])

In [61]:
np.sort(array2)

array([[0.07, 0.28, 0.46, 0.48, 0.6 ],
       [0.13, 0.37, 0.6 , 0.6 , 0.63],
       [0.17, 0.2 , 0.22, 0.59, 0.92]])

In [62]:
array2<0.3

array([[ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True,  True,  True, False, False]])

In [63]:
np.sort(array2,axis=0) # across row its getting sorted

array([[0.07, 0.2 , 0.22, 0.48, 0.6 ],
       [0.13, 0.28, 0.46, 0.59, 0.63],
       [0.17, 0.37, 0.6 , 0.6 , 0.92]])

In [64]:
np.sort(array2,axis=1) # across coll its getting sorted

array([[0.07, 0.28, 0.46, 0.48, 0.6 ],
       [0.13, 0.37, 0.6 , 0.6 , 0.63],
       [0.17, 0.2 , 0.22, 0.59, 0.92]])

In [65]:
array2[0,0]

0.07

In [66]:
array2[1,2]

0.6

In [67]:
array2[1:3,1:3]

array([[0.37, 0.6 ],
       [0.2 , 0.22]])

In [68]:
array2

array([[0.07, 0.28, 0.46, 0.48, 0.6 ],
       [0.13, 0.37, 0.6 , 0.6 , 0.63],
       [0.17, 0.2 , 0.22, 0.59, 0.92]])

In [69]:
array2.cumsum() # cummalatice sum

array([0.07, 0.35, 0.81, 1.29, 1.89, 2.02, 2.39, 2.99, 3.59, 4.22, 4.39,
       4.59, 4.81, 5.4 , 6.32])

In [70]:
array2.cumsum(axis=0) # accross row
array2.cumsum(axis=1) # accross col

array([[0.07, 0.28, 0.46, 0.48, 0.6 ],
       [0.2 , 0.65, 1.06, 1.08, 1.23],
       [0.37, 0.85, 1.28, 1.67, 2.15]])

array([[0.07, 0.35, 0.81, 1.29, 1.89],
       [0.13, 0.5 , 1.1 , 1.7 , 2.33],
       [0.17, 0.37, 0.59, 1.18, 2.1 ]])

In [71]:
indexing=np.round(np.random.random(64).reshape(16,4),2)
indexing

array([[0.35, 0.13, 0.64, 0.14],
       [0.68, 0.9 , 0.88, 0.42],
       [0.73, 0.21, 0.88, 0.42],
       [0.56, 0.06, 0.11, 0.21],
       [0.83, 0.17, 0.86, 0.98],
       [0.27, 0.38, 0.2 , 0.15],
       [0.4 , 0.61, 0.24, 0.83],
       [0.9 , 0.85, 0.74, 0.34],
       [0.97, 0.67, 0.12, 0.32],
       [0.2 , 0.82, 0.06, 0.31],
       [0.01, 0.92, 0.61, 0.27],
       [0.16, 0.3 , 0.11, 0.93],
       [0.95, 0.78, 0.05, 0.35],
       [0.84, 0.6 , 0.2 , 0.77],
       [0.27, 0.98, 0.29, 1.  ],
       [0.96, 0.55, 0.67, 0.47]])

**Indexing and linespacing revisited**

<img src="F:\\UPX_TechM\\Data Analytic\\Practicals\\Session\\Index.jpg"></img>

In [72]:
indexing[0,0:]
indexing[:,0:6]

array([0.35, 0.13, 0.64, 0.14])

array([[0.35, 0.13, 0.64, 0.14],
       [0.68, 0.9 , 0.88, 0.42],
       [0.73, 0.21, 0.88, 0.42],
       [0.56, 0.06, 0.11, 0.21],
       [0.83, 0.17, 0.86, 0.98],
       [0.27, 0.38, 0.2 , 0.15],
       [0.4 , 0.61, 0.24, 0.83],
       [0.9 , 0.85, 0.74, 0.34],
       [0.97, 0.67, 0.12, 0.32],
       [0.2 , 0.82, 0.06, 0.31],
       [0.01, 0.92, 0.61, 0.27],
       [0.16, 0.3 , 0.11, 0.93],
       [0.95, 0.78, 0.05, 0.35],
       [0.84, 0.6 , 0.2 , 0.77],
       [0.27, 0.98, 0.29, 1.  ],
       [0.96, 0.55, 0.67, 0.47]])

In [73]:
from matplotlib import pyplot as py

In [74]:
sin_indexing=np.sin(indexing)

In [75]:
sin_indexing

array([[0.34289781, 0.12963414, 0.59719544, 0.13954311],
       [0.62879302, 0.78332691, 0.77073888, 0.40776045],
       [0.66686964, 0.2084599 , 0.77073888, 0.40776045],
       [0.5311862 , 0.05996401, 0.1097783 , 0.2084599 ],
       [0.73793137, 0.16918235, 0.75784256, 0.83049737],
       [0.26673144, 0.37092047, 0.19866933, 0.14943813],
       [0.38941834, 0.57286746, 0.23770263, 0.73793137],
       [0.78332691, 0.75128041, 0.67428791, 0.33348709],
       [0.82488571, 0.62098599, 0.11971221, 0.31456656],
       [0.19866933, 0.73114583, 0.05996401, 0.30505864],
       [0.00999983, 0.79560162, 0.57286746, 0.26673144],
       [0.15931821, 0.29552021, 0.1097783 , 0.80161994],
       [0.8134155 , 0.70327942, 0.04997917, 0.34289781],
       [0.74464312, 0.56464247, 0.19866933, 0.69613524],
       [0.26673144, 0.83049737, 0.28595223, 0.84147098],
       [0.81919157, 0.52268723, 0.62098599, 0.45288629]])

**Pandas**
```
Sit on top of numpy
```
```
It has tabular struc
```
```
data mani, clean, merging, pivot anything to do with data
```


In [76]:
import pandas as pd

In [81]:
emp=pd.read_csv(Dataset+"\\employees.csv")

In [82]:
emp.head()# top 5 rows

Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
0  677509        Drs.       Lois              H    Walker      F   
1  940761         Ms.     Brenda              S  Robinson      F   
2  428945         Dr.        Joe              W  Robinson      M   
3  408351        Drs.      Diane              I     Evans      F   
4  193819         Mr.   Benjamin              R   Russell      M   

                         E Mail     Father's Name       Mother's Name  \
0       lois.walker@hotmail.com     Donald Walker        Helen Walker   
1     brenda.robinson@gmail.com  Raymond Robinson       Judy Robinson   
2        joe.robinson@gmail.com    Scott Robinson  Stephanie Robinson   
3         diane.evans@yahoo.com       Jason Evans      Michelle Evans   
4  benjamin.russell@charter.net   Gregory Russell   Elizabeth Russell   

  Mother's Maiden Name       ...                SSN    Phone No.   \
0                Lewis       ...        467-99-4677  303-572-8492   
1                Perry       ...        537-71-4566  225-945-4954   
2               Taylor       ...        025-92-3584  219-904-2161   
3                Allen       ...        314-35-9851  215-793-6791   
4               Nelson       ...        121-98-7248  262-404-2252   

     Place Name    County          City State    Zip     Region   User Name  \
0        Denver    Denver        Denver    CO  80224       West    lhwalker   
1     Stonewall   De Soto     Stonewall    LA  71078      South  bsrobinson   
2  Michigantown   Clinton  Michigantown    IN  46057    Midwest  jwrobinson   
3      Hydetown  Crawford      Hydetown    PA  16328  Northeast     dievans   
4       Fremont   Waupaca       Fremont    WI  54940    Midwest   brrussell   

         Password  
0   DCa}.T}X:v?NP  
1   TCo\j#Zg;SQ~o  
2    GO4$J8MiEh[A  
3   0gGRtp1HfL<r5  
4  Rd<Y8cp!@R;*%F  

[5 rows x 37 columns]

In [83]:
emp.tail() #bottom 5 rows

Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
95  639892         Mr.       Jose              K      Hill      M   
96  704709         Dr.     Harold              Z    Nelson      M   
97  461593         Ms.     Nicole              O      Ward      F   
98  392491        Mrs.    Theresa              R    Murphy      F   
99  495141        Drs.      Tammy              B     Young      F   

                      E Mail   Father's Name      Mother's Name  \
95     jose.hill@hotmail.com     Carlos Hill          Anna Hill   
96   harold.nelson@gmail.com  Richard Nelson      Pamela Nelson   
97     nicole.ward@yahoo.com      Ralph Ward         Julia Ward   
98  theresa.murphy@gmail.com   George Murphy  Jacqueline Murphy   
99   tammy.young@comcast.net    Andrew Young       Brenda Young   

   Mother's Maiden Name       ...                 SSN    Phone No.   \
95                Hayes       ...         171-86-3825  228-245-5000   
96                Smith       ...         456-99-2066  217-555-9216   
97                  Lee       ...         196-84-2551  231-761-7861   
98             Peterson       ...         249-99-8801  907-356-1555   
99             Robinson       ...         771-02-7046  231-290-3075   

      Place Name              County          City State    Zip   Region  \
95        Biloxi            Harrison        Biloxi    MS  39532    South   
96  Carol Stream        Carol Stream  Carol Stream    IL  60351  Midwest   
97       Detroit               Wayne       Detroit    MI  48278  Midwest   
98      Mc Grath  Yukon-Koyukuk (CA)      Mc Grath    AK  99627     West   
99          Alma             Gratiot          Alma    MI  48801  Midwest   

    User Name         Password  
95     jkhill  a_!SKb6h3?w*Mad  
96   hznelson      z/-hEz3&^q5  
97     noward   AUe6s0@:@]A3Ze  
98   trmurphy        V]PGw>4h9  
99    tbyoung  d6!&xu12A1H^i![  

[5 rows x 37 columns]

In [84]:
type(emp)

pandas.core.frame.DataFrame

In [85]:
emp.head(10) # top 10 rows

Emp ID Name Prefix First Name Middle Initial Last Name Gender  \
0  677509        Drs.       Lois              H    Walker      F   
1  940761         Ms.     Brenda              S  Robinson      F   
2  428945         Dr.        Joe              W  Robinson      M   
3  408351        Drs.      Diane              I     Evans      F   
4  193819         Mr.   Benjamin              R   Russell      M   
5  499687         Mr.    Patrick              F    Bailey      M   
6  539712         Ms.      Nancy              T     Baker      F   
7  380086        Mrs.      Carol              V    Murphy      F   
8  477616        Hon.    Frances              B     Young      F   
9  162402        Hon.      Diana              T  Peterson      F   

                         E Mail      Father's Name       Mother's Name  \
0       lois.walker@hotmail.com      Donald Walker        Helen Walker   
1     brenda.robinson@gmail.com   Raymond Robinson       Judy Robinson   
2        joe.robinson@gmail.com     Scott Robinson  Stephanie Robinson   
3         diane.evans@yahoo.com        Jason Evans      Michelle Evans   
4  benjamin.russell@charter.net    Gregory Russell   Elizabeth Russell   
5        patrick.bailey@aol.com       Ralph Bailey        Laura Bailey   
6            nancy.baker@bp.com        Scott Baker          Judy Baker   
7        carol.murphy@gmail.com      Eugene Murphy    Katherine Murphy   
8       frances.young@gmail.com         Fred Young       Lillian Young   
9  diana.peterson@hotmail.co.uk  Jonathan Peterson  Christina Peterson   

  Mother's Maiden Name       ...                 SSN    Phone No.   \
0                Lewis       ...         467-99-4677  303-572-8492   
1                Perry       ...         537-71-4566  225-945-4954   
2               Taylor       ...         025-92-3584  219-904-2161   
3                Allen       ...         314-35-9851  215-793-6791   
4               Nelson       ...         121-98-7248  262-404-2252   
5            Henderson       ...         439-99-7721  319-812-6957   
6               Thomas       ...         641-29-2071  229-336-5117   
7             Peterson       ...         423-67-7023  216-336-0009   
8                 Diaz       ...         028-92-8912  210-819-9765   
9                 Ross       ...         512-33-6767  479-783-5656   

       Place Name    County            City State    Zip     Region  \
0          Denver    Denver          Denver    CO  80224       West   
1       Stonewall   De Soto       Stonewall    LA  71078      South   
2    Michigantown   Clinton    Michigantown    IN  46057    Midwest   
3        Hydetown  Crawford        Hydetown    PA  16328  Northeast   
4         Fremont   Waupaca         Fremont    WI  54940    Midwest   
5       Macksburg   Madison       Macksburg    IA  50155    Midwest   
6         Atlanta    Fulton         Atlanta    GA  30334      South   
7     Blanchester   Clinton     Blanchester    OH  45107    Midwest   
8         Delmita     Starr         Delmita    TX  78536      South   
9  Eureka Springs   Carroll  Eureka Springs    AR  72632      South   

    User Name         Password  
0    lhwalker    DCa}.T}X:v?NP  
1  bsrobinson    TCo\j#Zg;SQ~o  
2  jwrobinson     GO4$J8MiEh[A  
3     dievans    0gGRtp1HfL<r5  
4   brrussell   Rd<Y8cp!@R;*%F  
5    pfbailey         K7&5aY/*  
6     ntbaker  xJdKlAcYQhT_BE#  
7    cvmurphy     Uc+VG%vuZU<k  
8     fbyoung      K}^USc0l7[A  
9  dtpeterson   3o8>v&tYxjyEAo  

[10 rows x 37 columns]

In [86]:
emp.columns

Index(['Emp ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E Mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='object')

In [87]:
emp.sample(10) # random 10 records

Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
8   477616        Hon.    Frances              B       Young      F   
62  758872         Mr.      Henry              Y     Jenkins      M   
82  761821         Mr.     Ernest              G  Washington      M   
16  912990         Mr.     Joshua              T     Stewart      M   
89  212893         Ms.      Janet              Y   Henderson      F   
94  489424         Dr.    Phillip              F       White      M   
48  363065        Drs.      Nancy              L       Jones      F   
98  392491        Mrs.    Theresa              R      Murphy      F   
57  515103         Ms.       Anne              A       Perez      F   
0   677509        Drs.       Lois              H      Walker      F   

                          E Mail      Father's Name       Mother's Name  \
8        frances.young@gmail.com         Fred Young       Lillian Young   
62     henry.jenkins@hotmail.com     Albert Jenkins     Beverly Jenkins   
82     ernest.washington@msn.com  Johnny Washington  Shirley Washington   
16       joshua.stewart@yahoo.ca       Todd Stewart      Martha Stewart   
89  janet.henderson@ntlworld.com    Jerry Henderson     Julie Henderson   
94       phillip.white@gmail.com       Harold White       Frances White   
48         nancy.jones@gmail.com       Eugene Jones        Sandra Jones   
98      theresa.murphy@gmail.com      George Murphy   Jacqueline Murphy   
57      anne.perez@sbcglobal.net      Douglas Perez         Doris Perez   
0        lois.walker@hotmail.com      Donald Walker        Helen Walker   

   Mother's Maiden Name       ...                SSN    Phone No.   \
8                  Diaz       ...        028-92-8912  210-819-9765   
62               Murphy       ...        499-29-3125  314-731-7135   
82               Harris       ...        178-86-1878  212-596-1659   
16                Jones       ...        755-07-3676  217-279-9342   
89               Cooper       ...        018-94-7340  239-769-6347   
94               Carter       ...        447-27-9469  503-668-6592   
48              Jenkins       ...        681-24-3165  212-825-1930   
98             Peterson       ...        249-99-8801  907-356-1555   
57               Bailey       ...        594-99-9091  423-837-3338   
0                 Lewis       ...        467-99-4677  303-572-8492   

       Place Name              County           City State    Zip     Region  \
8         Delmita               Starr        Delmita    TX  78536      South   
62      Riverside              Platte      Riverside    MO  64150    Midwest   
82   Saranac Lake            Franklin   Saranac Lake    NY  12983  Northeast   
16    New Douglas             Madison    New Douglas    IL  62074    Midwest   
89          Miami          Miami-Dade          Miami    FL  33166      South   
94       Mapleton                Lane       Mapleton    OR  97453       West   
48  New York City            New York  New York City    NY  10087  Northeast   
98       Mc Grath  Yukon-Koyukuk (CA)       Mc Grath    AK  99627       West   
57     Cookeville              Putnam     Cookeville    TN  38505      South   
0          Denver              Denver         Denver    CO  80224       West   

       User Name        Password  
8        fbyoung     K}^USc0l7[A  
62     hyjenkins        zPnRU5Bo  
82  egwashington        B\Wb^6W-  
16     jtstewart      K?vi9BBznj  
89   jyhenderson      g-oCs-L/za  
94       pfwhite  8<Mc.5]eu.*C8.  
48       nljones   J}HJq/zVF-Aq2  
98      trmurphy       V]PGw>4h9  
57       aaperez        y;n9A#}b  
0       lhwalker   DCa}.T}X:v?NP  

[10 rows x 37 columns]

In [88]:
emp.shape

(100, 37)

In [89]:
emp.describe()

Emp ID  Age in Yrs.  Weight in Kgs.  Year of Joining  \
count     100.00000   100.000000      100.000000       100.000000   
mean   547652.10000    39.238700       58.080000      2008.120000   
std    257664.16679    12.066252       12.294106         8.642484   
min    134841.00000    21.100000       40.000000      1983.000000   
25%    328643.75000    28.177500       50.000000      2003.000000   
50%    497414.00000    37.595000       56.000000      2010.500000   
75%    766040.00000    49.900000       61.250000      2015.000000   
max    979607.00000    59.470000       90.000000      2017.000000   

       Month of Joining  Day of Joining  Age in Company (Years)  \
count        100.000000      100.000000              100.000000   
mean           6.250000       16.370000                8.978400   
std            3.453515        9.403046                8.657358   
min            1.000000        1.000000                0.020000   
25%            3.000000        7.000000                2.152500   
50%            7.000000       18.000000                6.435000   
75%            8.250000       24.000000               13.762500   
max           12.000000       31.000000               34.520000   

              Salary           Zip  
count     100.000000    100.000000  
mean   119738.090000  53011.230000  
std     46185.278194  23007.336848  
min     42005.000000   3867.000000  
25%     83979.750000  37580.500000  
50%    118049.500000  52855.000000  
75%    162509.250000  69514.500000  
max    197537.000000  99791.000000

In [110]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 37 columns):
Emp ID                    100 non-null int64
Name Prefix               100 non-null object
First Name                100 non-null object
Middle Initial            100 non-null object
Last Name                 100 non-null object
Gender                    100 non-null object
E Mail                    100 non-null object
Father's Name             100 non-null object
Mother's Name             100 non-null object
Mother's Maiden Name      100 non-null object
Date of Birth             100 non-null object
Time of Birth             100 non-null object
Age in Yrs.               100 non-null float64
Weight in Kgs.            100 non-null int64
Date of Joining           100 non-null object
Quarter of Joining        100 non-null object
Half of Joining           100 non-null object
Year of Joining           100 non-null int64
Month of Joining          100 non-null int64
Month Name of Joining    