# NUMPY
```
The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.
```

<img src="Numpy_arrayType.png" ></img>

In [1]:
import numpy as np
from numpy import array

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [23]:
Dataset="../Datasets"

In [4]:
# Creating an 1D array
a=np.array([1,2,3])
print("Below is the example of 1D array")
a.ndim
a.shape
a

Below is the example of 1D array


1

(3,)

array([1, 2, 3])

In [5]:
# Creating an 2D array
b=np.array([(1,2,3),(3,4,5)], dtype=int)
print("Below is the example of 2D array")
b.ndim
b.shape
b

Below is the example of 2D array


2

(2, 3)

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
# Creating an 3D array
c=np.array([[(1,2,3), (4,5,6),(7,8,9)], [(10,11,12),(13,14,15), (16,17,18)],[(19,20,21),(22,23,24), (25,26,27)]], dtype=np.int16)
print("Below is the example of 3D array")
c.ndim
c.shape
c.dtype
c

Below is the example of 3D array


3

(3, 3, 3)

dtype('int16')

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int16)

In [7]:
# Creating an 4D array
d=np.array([([(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]),([(13,14,15), (16,17,18)], [(19,20,21), (22,23,24)])], dtype=int)
print("Below is the example of 4D array")
d.ndim
d.shape
d.dtype
d.strides
d

Below is the example of 4D array


4

(2, 2, 2, 3)

dtype('int32')

(48, 24, 12, 4)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [8]:
d[0]
d[0][0]
d[0][0][0]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3])

In [9]:
d[1]
d[1][0]
d[1][0][0]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

array([[13, 14, 15],
       [16, 17, 18]])

array([13, 14, 15])

In [10]:
c
c.shape
c.dtype
c.strides

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int16)

(3, 3, 3)

dtype('int16')

(18, 6, 2)

**Creating array as place holder for future assignment**
1. One array
2. Zero array
3. random array
3. Empty array
5. full array

In [11]:
np.ones(shape=(4,4,5))
#Above is similar to below initialization
np.ones((2,4,5))

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [12]:
np.zeros(shape=(2,3,4), dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [13]:
np.random.random((2,4))

array([[ 0.96766665,  0.93462592,  0.12023969,  0.691788  ],
       [ 0.0278142 ,  0.92663279,  0.93232824,  0.09224612]])

In [14]:
np.empty((3,3,3))

array([[[  4.11719832e-312,   0.00000000e+000,   1.01853707e+248],
        [  1.10175982e+025,   5.07297946e-038,   4.75968491e-038],
        [  1.66322966e-076,   5.85385535e-144,   2.14027814e+161]],

       [[  5.04621383e+180,   4.50618615e-144,   7.79952704e-143],
        [  4.40048996e+025,   5.68476401e+015,   2.31697092e-052],
        [  3.70234940e-033,   2.16385138e+190,   8.37170577e-144]],

       [[  3.51151606e+151,   1.04816985e-142,   4.82337433e+228],
        [  5.18315232e-144,   1.16097020e-028,   1.48340347e-076],
        [  4.17576316e-057,   6.81784476e-038,   2.62459080e-306]]])

In [15]:
np.full(shape=(3,4,3),fill_value=7)
# This same as below
np.full((3,4,3),7)


array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

#### Linespace and Arrange create an array of evenly-spaced values
**Linespace**
``` 
Last value of the three argument that are passed in the code chunk below designates the step value
```
**Arrange**
``` 
Last value of the three argument that are passed in the code chunk below designates number of samples or step value.
```

In [16]:
np.linspace(0,2,5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [17]:
np.arange(0,11,5)

array([ 0,  5, 10])

**Creating identity Matrix**
1. eye
2. identity

In [18]:
np.eye(N=3,dtype=np.int16)
np.identity(n=3,dtype=np.int16)
np.array([(1,0,0), (0,1,0),(0,0,1)])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Load NumPy Arrays From Text

In [24]:
data1=np.loadtxt(Dataset+"/emp.txt",unpack=True,delimiter=' ', dtype=np.str)

In [25]:
data2=np.genfromtxt(Dataset+"\\emp1.txt",unpack=True,delimiter='\t', dtype=np.str,filling_values='M', missing_values='M')

In [26]:
data1

array([['677509', '940761', '428945', '408351', '193819', '499687',
        '539712', '380086', '477616', '162402', '231469', '153989'],
       ['Dr', 'Ms', 'Dr', 'Dr', 'Mr', 'Mr', 'Ms', 'Mrs', 'Hon', 'Hon',
        'Mr', 'Prof'],
       ['Lois', 'Brenda', 'Joe', 'Diane', 'Benjamin', 'Patrick', 'Nancy',
        'Carol', 'Frances', 'Diana', 'Ralph', 'Jack'],
       ['H', 'S', 'W', 'I', 'R', 'F', 'T', 'V', 'B', 'T', 'L', 'C'],
       ['Walker', 'Robinson', 'Robinson', 'Evans', 'Russell', 'Bailey',
        'Baker', 'Murphy', 'Young', 'Peterson', 'Flores', 'Alexander'],
       ['F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F', 'F', 'M', 'M'],
       ['lois.walker@hotmail.com', 'brenda.robinson@gmail.com',
        'joe.robinson@gmail.com', 'diane.evans@yahoo.com',
        'benjamin.russell@charter.net', 'patrick.bailey@aol.com',
        'nancy.baker@bp.com', 'carol.murphy@gmail.com',
        'frances.young@gmail.com', 'diana.peterson@hotmail.co.uk',
        'ralph.flores@yahoo.com', 'jack.alexan

In [27]:
data2.ndim

2

In [28]:
a=[1,2,3]
b=[4,5,6]
c=a+b
c
type(c)

[1, 2, 3, 4, 5, 6]

list

In [29]:
# This will throw error is division and multiplication  is not allowed in list
distance=[45,50,35]
speed=[5,10,7]
time =distance/speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [30]:
dist=np.array(distance)
spd=np.array(speed)
t=dist/spd

In [31]:
t
t.shape
t.ndim
t.dtype
len(t)
t.size
t.dtype.name
int_t=t.astype(np.int32)
int_t
int_t.dtype

array([ 9.,  5.,  5.])

(3,)

1

dtype('float64')

3

3

'float64'

array([9, 5, 5])

dtype('int32')

In [32]:
c=np.array(np.arange(1,37,2)) # We are generating array starting from 1 and increament to 5 till 23

In [33]:
c
c.size

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

18

In [34]:
reshaped_2d=c.reshape(6,3)
reshaped_2d.ndim
reshaped_2d

2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [35]:
reshaped_3d=c.reshape(3,3,2)
reshaped_3d.ndim
reshaped_3d
reshaped_3d.shape
reshaped_3d.size
reshaped_3d.dtype
reshaped_3d.max()
reshaped_3d.min()
reshaped_3d.mean()

3

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]],

       [[25, 27],
        [29, 31],
        [33, 35]]])

(3, 3, 2)

18

dtype('int32')

35

1

18.0

In [36]:
linspc_array=np.array(np.linspace(1,100,48))

In [37]:
linspc_array.round(2)
np.round(linspc_array,0)

array([   1.  ,    3.11,    5.21,    7.32,    9.43,   11.53,   13.64,
         15.74,   17.85,   19.96,   22.06,   24.17,   26.28,   28.38,
         30.49,   32.6 ,   34.7 ,   36.81,   38.91,   41.02,   43.13,
         45.23,   47.34,   49.45,   51.55,   53.66,   55.77,   57.87,
         59.98,   62.09,   64.19,   66.3 ,   68.4 ,   70.51,   72.62,
         74.72,   76.83,   78.94,   81.04,   83.15,   85.26,   87.36,
         89.47,   91.57,   93.68,   95.79,   97.89,  100.  ])

array([   1.,    3.,    5.,    7.,    9.,   12.,   14.,   16.,   18.,
         20.,   22.,   24.,   26.,   28.,   30.,   33.,   35.,   37.,
         39.,   41.,   43.,   45.,   47.,   49.,   52.,   54.,   56.,
         58.,   60.,   62.,   64.,   66.,   68.,   71.,   73.,   75.,
         77.,   79.,   81.,   83.,   85.,   87.,   89.,   92.,   94.,
         96.,   98.,  100.])

In [38]:
linspc_arr_3d=np.round(linspc_array,0).reshape(2,4,6)

In [39]:
linspc_arr_3d
linspc_arr_3d.ndim


array([[[   1.,    3.,    5.,    7.,    9.,   12.],
        [  14.,   16.,   18.,   20.,   22.,   24.],
        [  26.,   28.,   30.,   33.,   35.,   37.],
        [  39.,   41.,   43.,   45.,   47.,   49.]],

       [[  52.,   54.,   56.,   58.,   60.,   62.],
        [  64.,   66.,   68.,   71.,   73.,   75.],
        [  77.,   79.,   81.,   83.,   85.,   87.],
        [  89.,   92.,   94.,   96.,   98.,  100.]]])

3

In [40]:
data2=np.array([(1,2,3,4),(5,6,7,8)])

In [41]:
data2.ndim
data2.size
data2.shape
data2.dtype

2

8

(2, 4)

dtype('int32')

In [42]:
zeros=np.zeros(10).reshape(2,5)

In [43]:
zeros

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [44]:
np.zeros((2,3,5),dtype=np.int16)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int16)