# NUMPY
```
The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.
```

<img src="Numpy_arrayType.png" ></img>

In [1]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [97]:
Dataset="F:\\UPX_TechM\\Data Analytic\\Practicals\\Datasets"

In [3]:
# Creating an 1D array
a=np.array([1,2,3])
print("Below is the example of 1D array")
a.ndim
a.shape
a

Below is the example of 1D array


1

(3,)

array([1, 2, 3])

In [4]:
# Creating an 2D array
b=np.array([(1,2,3),(3,4,5)], dtype=int)
print("Below is the example of 2D array")
b.ndim
b.shape
b

Below is the example of 2D array


2

(2, 3)

array([[1, 2, 3],
       [3, 4, 5]])

In [45]:
# Creating an 3D array
c=np.array([[(1,2,3), (4,5,6),(7,8,9)], [(10,11,12),(13,14,15), (16,17,18)],[(19,20,21),(22,23,24), (25,26,27)]], dtype=np.int16)
print("Below is the example of 3D array")
c.ndim
c.shape
c.dtype
c

Below is the example of 3D array


3

(3, 3, 3)

dtype('int16')

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int16)

In [46]:
# Creating an 4D array
d=np.array([([(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]),([(13,14,15), (16,17,18)], [(19,20,21), (22,23,24)])], dtype=int)
print("Below is the example of 4D array")
d.ndim
d.shape
d.dtype
d.strides
d

Below is the example of 4D array


4

(2, 2, 2, 3)

dtype('int32')

(48, 24, 12, 4)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [47]:
d[0]
d[0][0]
d[0][0][0]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3])

In [48]:
d[1]
d[1][0]
d[1][0][0]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

array([[13, 14, 15],
       [16, 17, 18]])

array([13, 14, 15])

In [49]:
c
c.shape
c.dtype
c.strides

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int16)

(3, 3, 3)

dtype('int16')

(18, 6, 2)

**Creating array as place holder for future assignment**
1. One array
2. Zero array
3. random array
3. Empty array
5. full array

In [62]:
np.ones(shape=(4,4,5))
#Above is similar to below initialization
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [64]:
np.zeros(shape=(2,3,4), dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [69]:
np.random.random((2,4))

array([[0.16586505, 0.11702889, 0.23356279, 0.33075428],
       [0.25853308, 0.6569399 , 0.80690928, 0.66524595]])

In [70]:
np.empty((3,3,3))

array([[[1.12019154e-311, 1.12019097e-311, 1.12019336e-311],
        [1.12018988e-311, 1.12019011e-311, 1.12018874e-311],
        [1.12018892e-311, 1.12018877e-311, 1.12019050e-311]],

       [[1.12018891e-311, 1.12018937e-311, 1.12019097e-311],
        [1.12019097e-311, 1.12019336e-311, 1.12018955e-311],
        [1.12018937e-311, 1.12018892e-311, 1.12018937e-311]],

       [[1.12019215e-311, 1.12019325e-311, 1.12018925e-311],
        [1.12019097e-311, 1.12018937e-311, 1.12019154e-311],
        [1.12019266e-311, 1.12019154e-311, 1.12019097e-311]]])

In [76]:
np.full(shape=(3,4,3),fill_value=7)
# This same as below
np.full((3,4,3),7)


array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

#### Linespace and Arrange create an array of evenly-spaced values
**Linespace**
``` 
Last value of the three that are passed in the code chunk above designates the step value
```
**Arrange**
``` 
Last value of the three that are passed in the code chunk above designates number of samples
```

In [77]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [80]:
np.arange(0,11,5)

array([ 0,  5, 10])

**Creating identity Matrix**
1. eye
2. identity

In [95]:
np.eye(N=3,dtype=np.int16)
np.identity(n=3,dtype=np.int16)
np.array([(1,0,0), (0,1,0),(0,0,1)])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Load NumPy Arrays From Text

In [101]:
data=np.loadtxt(Dataset+"\\emp.txt")

ValueError: could not convert string to float: 'Drs.'