# Pandas

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

1. 1D data is called series data
2. 2D data is called dataframe data
3. 3D and above data is called panel data

In [2]:
Dataset="../Datasets"

In [3]:
cars_df=pd.read_csv(Dataset+'/cars.csv')

In [4]:
cars_df.head(20)

Model  Actual_MPG  Cylinders  Engine_Disp  Horsepower  \
0          amc ambassador dpl        15.0          8        390.0         190   
1                 amc gremlin        21.0          6        199.0          90   
2                  amc hornet        18.0          6        199.0          97   
3               amc rebel sst        16.0          8        304.0         150   
4     buick estate wagon (sw)        14.0          8        455.0         225   
5           buick skylark 320        15.0          8        350.0         165   
6   chevrolet chevelle malibu        18.0          8        307.0         130   
7            chevrolet impala        14.0          8        454.0         220   
8       chevrolet monte carlo        15.0          8        400.0         150   
9                   chevy c20        10.0          8        307.0         200   
10        dodge challenger se        15.0          8        383.0         170   
11                 dodge d200        11.0          8        318.0         210   
12                  ford f250        10.0          8        360.0         215   
13           ford galaxie 500        15.0          8        429.0         198   
14              ford maverick        21.0          6        200.0          85   
15                ford torino        17.0          8        302.0         140   
16                   hi 1200d         9.0          8        304.0         193   
17         plymouth 'cuda 340        14.0          8        340.0         160   
18            plymouth duster        22.0          6        198.0          95   
19          plymouth fury iii        14.0          8        440.0         215   

    Weight  Accelerate  Year    Origin  
0     3850         8.5    70  American  
1     2648        15.0    70  American  
2     2774        15.5    70  American  
3     3433        12.0    70  American  
4     3086        10.0    70  American  
5     3693        11.5    70  American  
6     3504        12.0    70  American  
7     4354         9.0    70  American  
8     3761         9.5    70  American  
9     4376        15.0    70  American  
10    3563        10.0    70  American  
11    4382        13.5    70  American  
12    4615        14.0    70  American  
13    4341        10.0    70  American  
14    2587        16.0    70  American  
15    3449        10.5    70  American  
16    4732        18.5    70  American  
17    3609         8.0    70  American  
18    2833        15.5    70  American  
19    4312         8.5    70  American

In [5]:
cars_df.tail(20)

Model  Actual_MPG  Cylinders  Engine_Disp  \
372               ford fairmont futura        24.0          4        140.0   
373                     ford granada l        22.0          6        232.0   
374                    ford mustang gl        27.0          4        140.0   
375                        ford ranger        28.0          4        120.0   
376                     mercury lynx l        36.0          4         98.0   
377  oldsmobile cutlass ciera (diesel)        38.0          6        262.0   
378             plymouth horizon miser        38.0          4        105.0   
379         pontiac j2000 se hatchback        31.0          4        112.0   
380                    pontiac phoenix        27.0          4        151.0   
381                volkswagen rabbit l        36.0          4        105.0   
382                          vw pickup        44.0          4         97.0   
383                      datsun 310 gx        38.0          4         91.0   
384                       honda accord        36.0          4        107.0   
385                        honda civic        38.0          4         91.0   
386                 honda civic (auto)        32.0          4         91.0   
387                   mazda glc custom        31.0          4         91.0   
388                 mazda glc custom l        37.0          4         91.0   
389                   nissan stanza xe        36.0          4        120.0   
390                   toyota celica gt        32.0          4        144.0   
391                     toyota corolla        34.0          4        108.0   

     Horsepower  Weight  Accelerate  Year    Origin  
372          92    2865        16.4    82  American  
373         112    2835        14.7    82  American  
374          86    2790        15.6    82  American  
375          79    2625        18.6    82  American  
376          70    2125        17.3    82  American  
377          85    3015        17.0    82  American  
378          63    2125        14.7    82  American  
379          85    2575        16.2    82  American  
380          90    2735        18.0    82  American  
381          74    1980        15.3    82  European  
382          52    2130        24.6    82  European  
383          67    1995        16.2    82  Japanese  
384          75    2205        14.5    82  Japanese  
385          67    1965        15.0    82  Japanese  
386          67    1965        15.7    82  Japanese  
387          68    1970        17.6    82  Japanese  
388          68    2025        18.2    82  Japanese  
389          88    2160        14.5    82  Japanese  
390          96    2665        13.9    82  Japanese  
391          70    2245        16.9    82  Japanese

In [6]:
cars_df.columns

Index(['Model', 'Actual_MPG', 'Cylinders', 'Engine_Disp', 'Horsepower',
       'Weight', 'Accelerate', 'Year', 'Origin'],
      dtype='object')

In [7]:
type(cars_df)

pandas.core.frame.DataFrame

In [8]:
cars_df.sample(20)

Model  Actual_MPG  Cylinders  Engine_Disp  \
28       toyota corona mark ii        24.0          4        113.0   
390           toyota celica gt        32.0          4        144.0   
155  chevroelt chevelle malibu        16.0          6        250.0   
378     plymouth horizon miser        38.0          4        105.0   
233              renault 5 gtl        36.0          4         79.0   
106           oldsmobile omega        11.0          8        350.0   
168              pontiac astro        23.0          4        140.0   
111           plymouth valiant        18.0          6        225.0   
67             ford pinto (sw)        22.0          4        122.0   
10         dodge challenger se        15.0          8        383.0   
281      buick skylark limited        28.4          4        151.0   
162                 ford pinto        23.0          4        140.0   
158             chevrolet nova        18.0          6        250.0   
313                  audi 4000        34.3          4         97.0   
82       toyota corona hardtop        24.0          4        113.0   
213             toyota mark ii        19.0          6        156.0   
175                volvo 244dl        22.0          4        121.0   
236                 datsun 810        22.0          6        146.0   
277              toyota corona        27.5          4        134.0   
217         chevrolet chevette        30.5          4         98.0   

     Horsepower  Weight  Accelerate  Year    Origin  
28           95    2372        15.0    70  Japanese  
390          96    2665        13.9    82  Japanese  
155         105    3897        18.5    75  American  
378          63    2125        14.7    82  American  
233          58    1825        18.6    77  European  
106         180    3664        11.0    73  American  
168          78    2592        18.5    75  American  
111         105    3121        16.5    73  American  
67           86    2395        16.0    72  American  
10          170    3563        10.0    70  American  
281          90    2670        16.0    79  American  
162          83    2639        17.0    75  American  
158         105    3459        16.0    75  American  
313          78    2188        15.8    80  European  
82           95    2278        15.5    72  Japanese  
213         108    2930        15.5    76  Japanese  
175          98    2945        14.5    75  European  
236          97    2815        14.5    77  Japanese  
277          95    2560        14.2    78  Japanese  
217          63    2051        17.0    77  American

In [9]:
cars_df.shape
cars_df.describe()

(392, 9)

Actual_MPG   Cylinders  Engine_Disp  Horsepower       Weight  \
count  392.000000  392.000000   392.000000  392.000000   392.000000   
mean    23.445918    5.471939   194.411990  104.469388  2977.584184   
std      7.805007    1.705783   104.644004   38.491160   849.402560   
min      9.000000    3.000000    68.000000   46.000000  1613.000000   
25%     17.000000    4.000000   105.000000   75.000000  2225.250000   
50%     22.750000    4.000000   151.000000   93.500000  2803.500000   
75%     29.000000    8.000000   275.750000  126.000000  3614.750000   
max     46.600000    8.000000   455.000000  230.000000  5140.000000   

       Accelerate        Year  
count  392.000000  392.000000  
mean    15.541327   75.979592  
std      2.758864    3.683737  
min      8.000000   70.000000  
25%     13.775000   73.000000  
50%     15.500000   76.000000  
75%     17.025000   79.000000  
max     24.800000   82.000000

In [10]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
Model          392 non-null object
Actual_MPG     392 non-null float64
Cylinders      392 non-null int64
Engine_Disp    392 non-null float64
Horsepower     392 non-null int64
Weight         392 non-null int64
Accelerate     392 non-null float64
Year           392 non-null int64
Origin         392 non-null object
dtypes: float64(3), int64(4), object(2)
memory usage: 27.6+ KB


**There are 3 type of Data structure in pandas**
1. Series: It is 1D array which assign index to each value.
2. Dataframe: It is 2D array. Its a tabular data structure.
3. Panel: It has 3 dimensional and more dimensional array.

In [12]:
series1= pd.Series([10,20,30,40])
series1

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
series1.values

array([10, 20, 30, 40], dtype=int64)

In [14]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
series2=pd.Series([10,20,30,40,50], index=['one','two','three','four','five'])

In [16]:
series2

one      10
two      20
three    30
four     40
five     50
dtype: int64

In [17]:
series2.values
series2.index

array([10, 20, 30, 40, 50], dtype=int64)

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [25]:
series2[['four','five']]
series2[3:] # Even if we create index pandas maintain default numeric index

four    40
five    50
dtype: int64

four    40
five    50
dtype: int64

In [28]:
series2+6
series2**2

one      16
two      26
three    36
four     46
five     56
dtype: int64

one       100
two       400
three     900
four     1600
five     2500
dtype: int64

**Filtering the data from series**

In [29]:
series2[series2>20]

three    30
four     40
five     50
dtype: int64

In [30]:
np.sqrt(series2)

one      3.162278
two      4.472136
three    5.477226
four     6.324555
five     7.071068
dtype: float64

In [39]:
year=[90,91,92,93,94,95]
f1={90:8,91:9,92:10,93:11,94:12,95:13}
firm1=pd.Series(f1,index=year) # Here we are converting dictionary into a series we can do the same with set, list, tuple

In [40]:
firm1

90     8
91     9
92    10
93    11
94    12
95    13
dtype: int64

In [43]:
f2={90:32,92:24,93:45,94:56}
firm2=pd.Series(f2,index=year) 
modified_firm2=pd.Series(f2) 

1. ```since we dont have any value assigned to key with number 91,95 which is part of index we have NaN for that index.```
2. ```Since we have not assigned year as index so it will take key in dictionary f2 as the key since there is no 91,95 key it will not have NaN.```

In [47]:
firm2 
modified_firm2

90    32.0
91     NaN
92    24.0
93    45.0
94    56.0
95     NaN
dtype: float64

90    32
92    24
93    45
94    56
dtype: int64

In [52]:
year=[90,91,92,93,94,95,96,97,98,99]
f3={93:10,94:34,95:78}
firm3=pd.Series(f3,index=year)
modified_firm3=pd.Series(f3)

In [55]:
firm3
firm3.index
firm3.values
modified_firm3
modified_firm3.values
modified_firm3.index

90     NaN
91     NaN
92     NaN
93    10.0
94    34.0
95    78.0
96     NaN
97     NaN
98     NaN
99     NaN
dtype: float64

Int64Index([90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype='int64')

array([nan, nan, nan, 10., 34., 78., nan, nan, nan, nan])

93    10
94    34
95    78
dtype: int64

array([10, 34, 78], dtype=int64)

Int64Index([93, 94, 95], dtype='int64')

```NaN indicate missing value or na in panda indicate missing value you can isnull() function to find if there is any null values```

In [51]:
firm3.isnull()
pd.isnull(firm3)

90     True
91     True
92     True
93    False
94    False
95    False
96     True
97     True
98     True
99     True
dtype: bool

90     True
91     True
92     True
93    False
94    False
95    False
96     True
97     True
98     True
99     True
dtype: bool

In [57]:
years_f4=[90,93]
f4={93:10,94:34,95:78}
firm4=pd.Series(f4,index=years_f4) 
firm4 #since 94 and 95 is not there in year list hence firm4 will not have value associated with 94,95 from f4

90     NaN
93    10.0
dtype: float64

In [59]:
pd.isnull(firm4)

90     True
93    False
dtype: bool

In [64]:
pd.isnull(firm3)
firm3[:]

90     True
91     True
92     True
93    False
94    False
95    False
96     True
97     True
98     True
99     True
dtype: bool

90     NaN
91     NaN
92     NaN
93    10.0
94    34.0
95    78.0
96     NaN
97     NaN
98     NaN
99     NaN
dtype: float64

In [83]:
dict1={'finance':10,'earning':5,'debt':8}
dict2={'finance':8,'compensation':4,'earning':9}
count1=pd.Series(dict1)
count1
count2=pd.Series(dict2)
count2
count3=count1+count2
count3
count3.values
count3.index

debt        8
earning     5
finance    10
dtype: int64

compensation    4
earning         9
finance         8
dtype: int64

compensation     NaN
debt             NaN
earning         14.0
finance         18.0
dtype: float64

array([nan, nan, 14., 18.])

Index(['compensation', 'debt', 'earning', 'finance'], dtype='object')

In [72]:
data=pd.DataFrame({'price':[95,25,81,78,89],
                   'ticker':['AXP','CSCO','DIS','MSFT','WMT'],
                   'company':['American Express','Cisco','Walt Disney','Microsoft','Walmart']})

In [86]:
data

company  price ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     81    DIS
3         Microsoft     78   MSFT
4           Walmart     89    WMT

In [90]:
data['company']

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [91]:
data['ticker']

0     AXP
1    CSCO
2     DIS
3    MSFT
4     WMT
Name: ticker, dtype: object

In [94]:
data[3:]

company  price ticker
3  Microsoft     78   MSFT
4    Walmart     89    WMT

1. loc primarily used with lable but can be used with index. It need atleast one lable
2. iloc is only use index for getting data

In [98]:
data.iloc[0:2,0:2]
data.iloc[1,1]

company  price
0  American Express     95
1             Cisco     25

25

In [99]:
data.iloc[3,2]

'MSFT'

In [102]:
data.iloc[2:4,]
data.iloc[2:4,:]

company  price ticker
2  Walt Disney     81    DIS
3    Microsoft     78   MSFT

company  price ticker
2  Walt Disney     81    DIS
3    Microsoft     78   MSFT

In [110]:
data.iloc[2:4,1]
data.iloc[2:4,1:]

2    81
3    78
Name: price, dtype: int64

price ticker
2     81    DIS
3     78   MSFT

In [121]:
data.iloc[0:4,:]

company  price ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     81    DIS
3         Microsoft     78   MSFT

In [138]:
data.loc[2:,['ticker','company']]

ticker      company
2    DIS  Walt Disney
3   MSFT    Microsoft
4    WMT      Walmart

In [136]:
data.loc[:,['price']]

price
0     95
1     25
2     81
3     78
4     89

In [139]:
data.loc[[0],:]

company  price ticker
0  American Express     95    AXP

In [140]:
data['company']

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [141]:
data.company

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [163]:
data[data.price>80]

company  price ticker  year
0  American Express     95    AXP  2014
2       Walt Disney     81    DIS  2014
4           Walmart     89    WMT  2014

In [161]:
data['year']=2014

In [164]:
data
data[data.price>80][1:]

company  price ticker  year
0  American Express     95    AXP  2014
1             Cisco     25   CSCO  2014
2       Walt Disney     81    DIS  2014
3         Microsoft     78   MSFT  2014
4           Walmart     89    WMT  2014

company  price ticker  year
2  Walt Disney     81    DIS  2014
4      Walmart     89    WMT  2014

In [165]:
data['pricesquared']=data.price**2

In [166]:
data

company  price ticker  year  pricesquared
0  American Express     95    AXP  2014          9025
1             Cisco     25   CSCO  2014           625
2       Walt Disney     81    DIS  2014          6561
3         Microsoft     78   MSFT  2014          6084
4           Walmart     89    WMT  2014          7921

In [167]:
data['sqrtprice']=np.sqrt(data.pricesquared)

In [168]:
data

company  price ticker  year  pricesquared  sqrtprice
0  American Express     95    AXP  2014          9025       95.0
1             Cisco     25   CSCO  2014           625       25.0
2       Walt Disney     81    DIS  2014          6561       81.0
3         Microsoft     78   MSFT  2014          6084       78.0
4           Walmart     89    WMT  2014          7921       89.0

In [170]:
del data['pricesquared']

In [171]:
data

company  price ticker  year  sqrtprice
0  American Express     95    AXP  2014       95.0
1             Cisco     25   CSCO  2014       25.0
2       Walt Disney     81    DIS  2014       81.0
3         Microsoft     78   MSFT  2014       78.0
4           Walmart     89    WMT  2014       89.0

In [197]:
data['pricesquared']=np.NaN
data['sqrtprice']=np.NaN

In [174]:
data

company  price ticker  year  sqrtprice  pricesquared
0  American Express     95    AXP  2014       95.0           NaN
1             Cisco     25   CSCO  2014       25.0           NaN
2       Walt Disney     81    DIS  2014       81.0           NaN
3         Microsoft     78   MSFT  2014       78.0           NaN
4           Walmart     89    WMT  2014       89.0           NaN

In [180]:
data['sequence']=np.arange(0,25,5)

In [198]:
data

company  price ticker  year  sqrtprice  pricesquared  sequence
0  American Express     95    AXP  2014        NaN           NaN         0
1             Cisco     25   CSCO  2014        NaN           NaN         5
2       Walt Disney     81    DIS  2014        NaN           NaN        10
3         Microsoft     78   MSFT  2014        NaN           NaN        15
4           Walmart     89    WMT  2014        NaN           NaN        20

In [199]:
data.values
data.shape
data.index
data
data.mean()
data.median()
data.std()
data.cumsum()
data.describe()
data.info()

array([['American Express', 95, 'AXP', 2014, nan, nan, 0],
       ['Cisco', 25, 'CSCO', 2014, nan, nan, 5],
       ['Walt Disney', 81, 'DIS', 2014, nan, nan, 10],
       ['Microsoft', 78, 'MSFT', 2014, nan, nan, 15],
       ['Walmart', 89, 'WMT', 2014, nan, nan, 20]], dtype=object)

(5, 7)

RangeIndex(start=0, stop=5, step=1)

company  price ticker  year  sqrtprice  pricesquared  sequence
0  American Express     95    AXP  2014        NaN           NaN         0
1             Cisco     25   CSCO  2014        NaN           NaN         5
2       Walt Disney     81    DIS  2014        NaN           NaN        10
3         Microsoft     78   MSFT  2014        NaN           NaN        15
4           Walmart     89    WMT  2014        NaN           NaN        20

price             73.6
year            2014.0
sqrtprice          NaN
pricesquared       NaN
sequence          10.0
dtype: float64

price             81.0
year            2014.0
sqrtprice          NaN
pricesquared       NaN
sequence          10.0
dtype: float64

price           27.978563
year             0.000000
sqrtprice             NaN
pricesquared          NaN
sequence         7.905694
dtype: float64

company price             ticker  \
0                                  American Express    95                AXP   
1                             American ExpressCisco   120            AXPCSCO   
2                  American ExpressCiscoWalt Disney   201         AXPCSCODIS   
3         American ExpressCiscoWalt DisneyMicrosoft   279     AXPCSCODISMSFT   
4  American ExpressCiscoWalt DisneyMicrosoftWalmart   368  AXPCSCODISMSFTWMT   

    year sqrtprice pricesquared sequence  
0   2014       NaN          NaN        0  
1   4028       NaN          NaN        5  
2   6042       NaN          NaN       15  
3   8056       NaN          NaN       30  
4  10070       NaN          NaN       50

price    year  sqrtprice  pricesquared   sequence
count   5.000000     5.0        0.0           0.0   5.000000
mean   73.600000  2014.0        NaN           NaN  10.000000
std    27.978563     0.0        NaN           NaN   7.905694
min    25.000000  2014.0        NaN           NaN   0.000000
25%    78.000000  2014.0        NaN           NaN   5.000000
50%    81.000000  2014.0        NaN           NaN  10.000000
75%    89.000000  2014.0        NaN           NaN  15.000000
max    95.000000  2014.0        NaN           NaN  20.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
company         5 non-null object
price           5 non-null int64
ticker          5 non-null object
year            5 non-null int64
sqrtprice       0 non-null float64
pricesquared    0 non-null float64
sequence        5 non-null int32
dtypes: float64(2), int32(1), int64(2), object(2)
memory usage: 340.0+ bytes
